a = int(input("İnteger Value: "))
b = str(input("String Value: "))
c = float(input("Float Value: "))
d = bool(input("Boolean Value: "))
e = complex(input("Complex Value:"))

print("Class :{}".format(type(a)))
print("Class :{}".format(type(b)))
print("Class :{}".format(type(c)))
print("Class :{}".format(type(d)))
print("Class :{}".format(type(e)))